#!/bin/bash
#
# Set file modification time to origin time for querydatas used in wfs tests.
# Modification time is returned as data resultTime, so it must be fixed in order to satisfy tests.
#
# BS-1310
#
querydatas=(
    pal/200808050933_pal_skandinavia_pinta.sqd
    pal/200808050729_pal_skandinavia_pinta.sqd
    harmonie/201705110343_harmonie_hybrid-cropped.sqd
    hirlam/201303180352_hirlam_eurooppa_pinta_cropped.sqd
)

realname=$(readlink -e $0) # Make sure we follow to real data directory even if symlinked
dir=$(dirname $realname)

cd "$dir"

modtimescript=modify_times.sh

if [ -x "/usr/bin/qdinfo" ] ; then
    echo "# Set modification times for certain data files" > $modtimescript.tmp
    for qd in ${querydatas[*]}
    do
	if [ ! -f "$qd" ]; then
	    echo "*** Missing file $qd"
	else
	    originTime=$(qdinfo -T "%Y-%m-%dT%H:%M:00" -q $qd | grep "^Origin time" | awk '{print $4}' | tr "T" " ")
            echo "Setting modification time $originTime for $qd"
            echo touch -m -d "\"$originTime\"" $qd >> $modtimescript.tmp
	fi
    done
    cmp -s $modtimescript $modtimescript.tmp || (
	echo "Target modification times for test data have changed"
	echo "Please commit `basename $modtimescript` as well"
	mv $modtimescript.tmp $modtimescript
    )
    rm -f $modtimescript.tmp
fi

. $modtimescript

